services:
  - type: web
    name: ocr-translation-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /health
    autoDeploy: true
